### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by williamoconnor** [Gooey-Dee-Bee/Ripple#65]
If someone drops a song from the search bar that has already been dropped in that region, then should it be a new drop, or just end up being a redrop?

**Comment by jrutz** [comment]
I don't remember if we'd discussed this in person: I think it should be a re-drop. Otherwise it'll encourage people to drop instead of re-drop and scroll through the playlist. Some people may get points they don't deserve if they're patient 0 on dropping the song but that just means they have good taste.

**Comment by AveryFerrante** [comment]
Right now I have it set up as a redrop. Even if they try a regular drop it will see it is a redrop and do stuff according
