### ISSUE TITLE
Says I'm logged in after getting error creating account

### ISSUE THREAD

**Issue by cknee217** [Gooey-Dee-Bee/Ripple#87]
After getting this same error with my gmail account (which I mentioned in another issue)
![screen shot 2015-04-27 at 10 44 29 am](https://cloud.githubusercontent.com/assets/8548541/7351402/913576ac-ecca-11e4-80d9-c9d558c75bff.png)

I pressed "back" and was taken to this screen where it says I am logged in. 

![screen shot 2015-04-27 at 10 52 29 am](https://cloud.githubusercontent.com/assets/8548541/7351624/e9f498e4-eccb-11e4-9d6c-258475187625.png)

Then I logged out from this account and couldn't log back in with it.

![screen shot 2015-04-27 at 10 57 58 am](https://cloud.githubusercontent.com/assets/8548541/7351692/6d55f07a-eccc-11e4-85cc-65db1e459225.png)

**Comment by AveryFerrante** [comment]
Well, judging by your url in the pictures, it looks like you have downloaded our site and you are running it locally. Therefore, I would imagine all the PHP file paths are wrong, since they are configured to run on our ec2. Also, I would assume you don't have a database set up on your local machine which matches what ours would be on our ec2. Our ec2 is 54.69.13.79/ripple/

Hopefully that will fix some of these issues.
